# Generated by Django 4.1.3 on 2022-11-26 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TravelApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='desc',
            field=models.TextField(default=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='img',
            field=models.ImageField(default=4334, upload_to='pics'),
            preserve_default=False,
        ),
    ]
